- id: doi:10.1038/s42256-023-00666-w
  type: paper
  description: An in vitro biological system of cultured brain cells has learned to play Pong. This feat opens up an avenue towards the convergence of biological and machine intelligence.
  date: 2023-06-01
  image: https://en.wikipedia.org/wiki/Nature_Machine_Intelligence#/media/File:Nature_Machine_Intelligence_journal_cover_volume_1_issue_1.png
  buttons:
    - type: website
      link: https://www.nature.com/articles/s42256-023-00666-w
  tags:
    - Biomedical engineering
    - Cognitive neuroscience
    - Problem solving

- id: arXiv:2412.14112
  image: https://simple.wikipedia.org/wiki/ArXiv#/media/File:ArXiv_logo_2022.png
